name: "Label 'stale' on PRs"
on:
  schedule:
    - cron: "30 1 * * *"

jobs:
  stale:
    permissions:
      pull-requests: write # to add labels and comments to PRs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-issue-stale: -1 # We don't want to address issues
          days-before-pr-stale: 60
          days-before-issue-close: -1 # We don't want to close issues in this action
          days-before-pr-close: -1 # We don't want to close PR in this action
          stale-pr-label: stale
          stale-pr-message: |
            This PR has been automatically marked as stale because it has no activity for 60 days.
            Please add a comment if you want to keep the issue open. Thank you for your contributions!
